# This is a basic workflow to help you get started with Actions

name: Flask-app workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests: 
    runs-on: ubuntu-latest
    
    
    steps:
      - uses: action/checkout@v2
      - name: Set up Python
        uses: action/setup-python@v2
        with:
          python-version: 3.8
          
       - name: Install dependencies
         run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .
      
      - name: Test with pytest
        run: pytest tests.py

  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repo
        users: action/checkout@v2
        
        
      - name: Push to Docker Hub
        users: docker/build-push-action@v1
        with:
          username: ${{ secret.DOCKER_USRNAME }}
          password: ${{ secret.DOCKER_PASSWORD }}
          repository: p1chkn/flask-app
          tag_with_ref: true

  deploy:
    runs_on: ubuntu-latest
    needs: build_and_push_to_docker_hur
    steps:
      - name: executing remote ssh commands to deploy
        users: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull p1chkn/flask-app
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker run --rm -d -p 5000:5000 p1chkn/flask-app
  
  send_message:
    runs-on: ubuntu-latest
    needs: deploy 
    steps:
      - name: send message
        users: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!